### PR TITLE
all: update to Gio 0.6 and Go 1.22

### LINKED ISSUE #7: share: [macos] invisible dialog
Under some circumstances, the MacOS dialog is displayed invisible.

### LINKED ISSUE #57: Explorer demo fails to run on Mac
Running off latest...

cd explorer/demo && go run .

OR

cd explorer/demo && go build .
cd explorer/demo && ./demo

```sh
github.com/gioui-plugins/gio-plugins/explorer
../explorer_macos.go:56:14: cannot use e.config.View (variable of type uintptr) as _Ctype_CFTypeRef value in variable declaration
../explorer_macos.go:85:14: cannot use e.config.View (variable of type uintptr) as _Ctype_CFTypeRef value in variable declaration
../explorer_macos.go:113:18: cannot use io.ReadCloser in union (io.ReadCloser contains methods)
```

### LINKED ISSUE #63: share demo bug with NewTheme function.
https://github.com/gioui-plugins/gio-plugins/blob/main/share/demo/main.go#L39

```sh
theme := material.NewTheme(gofont.Collection())
```

should just be:

```sh
theme := material.NewTheme()
```

### LINKED ISSUE #65: Upgrade to Gio 0.5
**Is your feature request related to a problem? Please describe.**
Currently, gio-plugins don't support Gio 0.5. 

**Describe the solution you'd like**
Make it compatible.

**Describe alternatives you've considered**
We need to refactor `plugin` package, and rewrite most demonstrations.

### PR DESCRIPTION
**Pull request by inkeliz**
That change uses the new gtx.Execute. This change makes compatible with Gio 0.6. The plugins.Install was removed and replaced by gioplugins.Event(), README was updated to reflect such change.

Also, the wasm-import and InkWASM to be compatible with Go 1.20+ versions. The Explorer package was updated to be compatible with standard version of Go Compiler.

Fix #57
Fix #65
Fix #63 
Fix #7 

EDIT:

It requires changes in Gio-Core (either https://github.com/gioui/gio/pull/136 or https://github.com/gioui/gio/pull/134 must get accepted upstream). Currently, it assumes that Gio is https://github.com/gioui/gio/pull/136. That is also why the current `go.mod` uses `replace` everywhere.

### CODE REVIEW

**Comment by ddkwork** [comment]
which gio branch you called?

**Comment by gedw99** [comment]
really hope that the GIO changes get through as this has been on hold for so long.

**Comment by inkeliz** [comment]
It don't work with `gtx.Event` or `gtx.Execute`, instead `gioplugins.Event(gtx, ...)` and `gioplugins.Execute(gtx, ...)` must be used. That makes possible to use without any Gio change, of couse it's worse and more confusing, but works. If eventually Gio adds support for custom event/filter then we can simply re-use the existent function.

The old `plugin.Install()` was moved and renamed to `gioplugins.Hijack(window)`.

**Comment by gedw99** [comment]
Thanks for the explanation @inkeliz 

 Well done . Amazing work.

I tested most of the plugins last night. All working for me. Works on windows arm64 too when I tried it.

**Pull request merged**
