### PR TITLE
Fix cookies and crashes on webview

### PR DESCRIPTION
**Pull request by inkeliz**
This changes fixes crashes on Windows (#59) and use secure-cookies when requested (on macOS).

### CODE REVIEW

**Comment by gedw99** [comment]
Nice one

I will try this on windows arm64 in UTM from my MAC

**Comment by gedw99** [comment]
on windows 11 arm64 I got:
```sh
[0405/010811.835:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

it opened and then created a folder called "gio-plugin-webview_windows_arm64.exe.WebView2", since the binary is called "gio-plugin-webview_windows_arm64.exe".

working on what's up...

**Comment by gedw99** [comment]
I installed WebView2 for Edge from https://go.microsoft.com/fwlink/p/?LinkId=2124703

same error ...

I installed directly from
https://developer.microsoft.com/en-gb/microsoft-edge/webview2/?form=MA13LH#download

same error ...

Shall I turn this into an issue ?
I can also install golang onto that instance and try it from there. 
I make the binary on a Mac using "CGO_ENABLED=1 GOOS=windows GOARCH=arm64 go build"

**Comment by inkeliz** [comment]
"Failed to unregister class Chrome_WidgetWin_0. Error = 0" happens when close the app right?

**Comment by gedw99** [comment]
hey @inkeliz 

No it’s a different sequence occurring.

Here is the sequence:

I go to the terminal so I can see the log output and open it from there.

I execute the .exe and the gui opens and you see a white background. 

then it creates a folder with various folders inside it relating to Webview2 I think.

then it crashes / closes and I can see the error output. 

The output was pretty long. I only posted the final error message here in this issue..

—-

This happens with or without the WebView2 for Edge installed.

—-

If you want more information , do not hesitate to ask.

**Comment by gedw99** [comment]
Btw it works fine on windows and64. A buddy tested it for me.

so seems to be a windows 11 arm64 related bug.

I run on mac and use  UTM to run windows 11 arm64 btw. Are you also on mac ?

**Comment by inkeliz** [comment]
Yes, I'm using mac (MacStudio M2). I never tested Windows on ARM64.

**Comment by gedw99** [comment]
UTM is awesome

https://mac.getutm.app/gallery/windows-11-arm

**Pull request merged**
